//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eidss.webclient.ReportService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReportService.IReportFacade")]
    public interface IReportFacade {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportHumAggregateCase", ReplyAction="http://tempuri.org/IReportFacade/ExportHumAggregateCaseResponse")]
        byte[] ExportHumAggregateCase(eidss.model.Reports.Common.AggregateModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportHumAggregateCaseSummary", ReplyAction="http://tempuri.org/IReportFacade/ExportHumAggregateCaseSummaryResponse")]
        byte[] ExportHumAggregateCaseSummary(eidss.model.Reports.Common.AggregateSummaryModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportHumCaseInvestigation", ReplyAction="http://tempuri.org/IReportFacade/ExportHumCaseInvestigationResponse")]
        byte[] ExportHumCaseInvestigation(eidss.model.Reports.Common.HumIdModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportHumUrgentyNotification", ReplyAction="http://tempuri.org/IReportFacade/ExportHumUrgentyNotificationResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.HumIdModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.AggregateActionsModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.VetIdModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimTestResultModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimTestModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimBatchTestModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.AggregateModel))]
        byte[] ExportHumUrgentyNotification(eidss.model.Reports.Common.BaseIdModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportHumDiagnosisToChangedDiagnosis", ReplyAction="http://tempuri.org/IReportFacade/ExportHumDiagnosisToChangedDiagnosisResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.KZ.ProphylacticModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.KZ.SanitaryModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.KZ.DiagnosticInvestigationModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.SummaryByRayonDiagnosisAgeGroupsModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.GG.Hum60BJournalModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.GG.IntermediateInfectiousDiseaseSurrogateModel))]
        byte[] ExportHumDiagnosisToChangedDiagnosis(eidss.model.Reports.Common.BaseIntervalModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportHumMonthlyMorbidityAndMortality", ReplyAction="http://tempuri.org/IReportFacade/ExportHumMonthlyMorbidityAndMortalityResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.GG.MonthInfectiousDiseaseModel))]
        byte[] ExportHumMonthlyMorbidityAndMortality(eidss.model.Reports.Common.BaseDateModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportHumSummaryOfInfectiousDiseases", ReplyAction="http://tempuri.org/IReportFacade/ExportHumSummaryOfInfectiousDiseasesResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.KZ.ProphylacticModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.KZ.SanitaryModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.KZ.DiagnosticInvestigationModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.SummaryByRayonDiagnosisAgeGroupsModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.GG.Hum60BJournalModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.GG.IntermediateInfectiousDiseaseSurrogateModel))]
        byte[] ExportHumSummaryOfInfectiousDiseases(eidss.model.Reports.Common.BaseIntervalModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportHumSerologyResearchCard", ReplyAction="http://tempuri.org/IReportFacade/ExportHumSerologyResearchCardResponse")]
        byte[] ExportHumSerologyResearchCard(eidss.model.Reports.GG.LabSampleModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportHumMicrobiologyResearchCard", ReplyAction="http://tempuri.org/IReportFacade/ExportHumMicrobiologyResearchCardResponse")]
        byte[] ExportHumMicrobiologyResearchCard(eidss.model.Reports.GG.LabSampleModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportHumAntibioticResistanceCard", ReplyAction="http://tempuri.org/IReportFacade/ExportHumAntibioticResistanceCardResponse")]
        byte[] ExportHumAntibioticResistanceCard(eidss.model.Reports.GG.LabSampleModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportHum60BJournal", ReplyAction="http://tempuri.org/IReportFacade/ExportHum60BJournalResponse")]
        byte[] ExportHum60BJournal(eidss.model.Reports.GG.Hum60BJournalModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportHumMonthInfectiousDisease", ReplyAction="http://tempuri.org/IReportFacade/ExportHumMonthInfectiousDiseaseResponse")]
        byte[] ExportHumMonthInfectiousDisease(eidss.model.Reports.GG.MonthInfectiousDiseaseModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportHumMonthInfectiousDiseaseNew", ReplyAction="http://tempuri.org/IReportFacade/ExportHumMonthInfectiousDiseaseNewResponse")]
        byte[] ExportHumMonthInfectiousDiseaseNew(eidss.model.Reports.GG.MonthInfectiousDiseaseModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportHumIntermediateMonthInfectiousDisease", ReplyAction="http://tempuri.org/IReportFacade/ExportHumIntermediateMonthInfectiousDiseaseRespo" +
            "nse")]
        byte[] ExportHumIntermediateMonthInfectiousDisease(eidss.model.Reports.GG.IntermediateInfectiousDiseaseSurrogateModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportHumIntermediateMonthInfectiousDiseaseNew", ReplyAction="http://tempuri.org/IReportFacade/ExportHumIntermediateMonthInfectiousDiseaseNewRe" +
            "sponse")]
        byte[] ExportHumIntermediateMonthInfectiousDiseaseNew(eidss.model.Reports.GG.IntermediateInfectiousDiseaseSurrogateModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportHumAnnualInfectiousDisease", ReplyAction="http://tempuri.org/IReportFacade/ExportHumAnnualInfectiousDiseaseResponse")]
        byte[] ExportHumAnnualInfectiousDisease(eidss.model.Reports.GG.AnnualInfectiousDiseaseModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportHumIntermediateAnnualInfectiousDisease", ReplyAction="http://tempuri.org/IReportFacade/ExportHumIntermediateAnnualInfectiousDiseaseResp" +
            "onse")]
        byte[] ExportHumIntermediateAnnualInfectiousDisease(eidss.model.Reports.GG.IntermediateInfectiousDiseaseSurrogateModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportHumFormN1", ReplyAction="http://tempuri.org/IReportFacade/ExportHumFormN1Response")]
        byte[] ExportHumFormN1(eidss.model.Reports.AZ.FormNo1SurrogateModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportHumDataQualityIndicators", ReplyAction="http://tempuri.org/IReportFacade/ExportHumDataQualityIndicatorsResponse")]
        byte[] ExportHumDataQualityIndicators(eidss.model.Reports.AZ.DataQualityIndicatorsModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportHumDataQualityIndicatorsRayons", ReplyAction="http://tempuri.org/IReportFacade/ExportHumDataQualityIndicatorsRayonsResponse")]
        byte[] ExportHumDataQualityIndicatorsRayons(eidss.model.Reports.AZ.DataQualityIndicatorsModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportHumSummaryByRayonDiagnosisAgeGroups", ReplyAction="http://tempuri.org/IReportFacade/ExportHumSummaryByRayonDiagnosisAgeGroupsRespons" +
            "e")]
        byte[] ExportHumSummaryByRayonDiagnosisAgeGroups(eidss.model.Reports.AZ.SummaryByRayonDiagnosisAgeGroupsModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportHumComparativeAZReport", ReplyAction="http://tempuri.org/IReportFacade/ExportHumComparativeAZReportResponse")]
        byte[] ExportHumComparativeAZReport(eidss.model.Reports.AZ.ComparativeSurrogateModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportHumExternalComparativeReport", ReplyAction="http://tempuri.org/IReportFacade/ExportHumExternalComparativeReportResponse")]
        byte[] ExportHumExternalComparativeReport(eidss.model.Reports.AZ.ExternalComparativeSurrogateModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportHumMainIndicatorsOfAFPSurveillance", ReplyAction="http://tempuri.org/IReportFacade/ExportHumMainIndicatorsOfAFPSurveillanceResponse" +
            "")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.DataQualityIndicatorsModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.VetLabSurrogateModel))]
        byte[] ExportHumMainIndicatorsOfAFPSurveillance(eidss.model.Reports.AZ.AFPModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportHumAdditionalIndicatorsOfAFPSurveillance", ReplyAction="http://tempuri.org/IReportFacade/ExportHumAdditionalIndicatorsOfAFPSurveillanceRe" +
            "sponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.DataQualityIndicatorsModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.VetLabSurrogateModel))]
        byte[] ExportHumAdditionalIndicatorsOfAFPSurveillance(eidss.model.Reports.AZ.AFPModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportHumWhoMeaslesRubellaReport", ReplyAction="http://tempuri.org/IReportFacade/ExportHumWhoMeaslesRubellaReportResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.GG.MonthInfectiousDiseaseModel))]
        byte[] ExportHumWhoMeaslesRubellaReport(eidss.model.Reports.Common.BaseDateModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportHumComparativeReportOfTwoYears", ReplyAction="http://tempuri.org/IReportFacade/ExportHumComparativeReportOfTwoYearsResponse")]
        byte[] ExportHumComparativeReportOfTwoYears(eidss.model.Reports.AZ.ComparativeTwoYearsSurrogateModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportVeterinaryCasesReport", ReplyAction="http://tempuri.org/IReportFacade/ExportVeterinaryCasesReportResponse")]
        byte[] ExportVeterinaryCasesReport(eidss.model.Reports.AZ.VetCasesSurrogateModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportVeterinaryLaboratoriesAZReport", ReplyAction="http://tempuri.org/IReportFacade/ExportVeterinaryLaboratoriesAZReportResponse")]
        byte[] ExportVeterinaryLaboratoriesAZReport(eidss.model.Reports.AZ.VetLabSurrogateModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportVetAggregateCase", ReplyAction="http://tempuri.org/IReportFacade/ExportVetAggregateCaseResponse")]
        byte[] ExportVetAggregateCase(eidss.model.Reports.Common.AggregateModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportVetAggregateCaseSummary", ReplyAction="http://tempuri.org/IReportFacade/ExportVetAggregateCaseSummaryResponse")]
        byte[] ExportVetAggregateCaseSummary(eidss.model.Reports.Common.AggregateSummaryModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportVetAggregateCaseActions", ReplyAction="http://tempuri.org/IReportFacade/ExportVetAggregateCaseActionsResponse")]
        byte[] ExportVetAggregateCaseActions(eidss.model.Reports.Common.AggregateActionsModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportVetAggregateCaseActionsSummary", ReplyAction="http://tempuri.org/IReportFacade/ExportVetAggregateCaseActionsSummaryResponse")]
        byte[] ExportVetAggregateCaseActionsSummary(eidss.model.Reports.Common.AggregateActionsSummaryModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportVetAvianInvestigation", ReplyAction="http://tempuri.org/IReportFacade/ExportVetAvianInvestigationResponse")]
        byte[] ExportVetAvianInvestigation(eidss.model.Reports.Common.VetIdModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportVetLivestockInvestigation", ReplyAction="http://tempuri.org/IReportFacade/ExportVetLivestockInvestigationResponse")]
        byte[] ExportVetLivestockInvestigation(eidss.model.Reports.Common.VetIdModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportVetActiveSurveillanceSampleCollected", ReplyAction="http://tempuri.org/IReportFacade/ExportVetActiveSurveillanceSampleCollectedRespon" +
            "se")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.HumIdModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.AggregateActionsModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.VetIdModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimTestResultModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimTestModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimBatchTestModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.AggregateModel))]
        byte[] ExportVetActiveSurveillanceSampleCollected(eidss.model.Reports.Common.BaseIdModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportVetSamplesCount", ReplyAction="http://tempuri.org/IReportFacade/ExportVetSamplesCountResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.FormNo1SurrogateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.AFPModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.DataQualityIndicatorsModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.VetLabSurrogateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.GG.AnnualInfectiousDiseaseModel))]
        byte[] ExportVetSamplesCount(eidss.model.Reports.Common.BaseYearModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportVetSamplesBySampleType", ReplyAction="http://tempuri.org/IReportFacade/ExportVetSamplesBySampleTypeResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.FormNo1SurrogateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.AFPModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.DataQualityIndicatorsModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.VetLabSurrogateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.GG.AnnualInfectiousDiseaseModel))]
        byte[] ExportVetSamplesBySampleType(eidss.model.Reports.Common.BaseYearModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportVetSamplesBySampleTypesWithinRegions", ReplyAction="http://tempuri.org/IReportFacade/ExportVetSamplesBySampleTypesWithinRegionsRespon" +
            "se")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.FormNo1SurrogateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.AFPModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.DataQualityIndicatorsModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.VetLabSurrogateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.GG.AnnualInfectiousDiseaseModel))]
        byte[] ExportVetSamplesBySampleTypesWithinRegions(eidss.model.Reports.Common.BaseYearModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportVetYearlySituation", ReplyAction="http://tempuri.org/IReportFacade/ExportVetYearlySituationResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.FormNo1SurrogateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.AFPModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.DataQualityIndicatorsModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.VetLabSurrogateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.GG.AnnualInfectiousDiseaseModel))]
        byte[] ExportVetYearlySituation(eidss.model.Reports.Common.BaseYearModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportVetActiveSurveillance", ReplyAction="http://tempuri.org/IReportFacade/ExportVetActiveSurveillanceResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.FormNo1SurrogateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.AFPModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.DataQualityIndicatorsModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.VetLabSurrogateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.GG.AnnualInfectiousDiseaseModel))]
        byte[] ExportVetActiveSurveillance(eidss.model.Reports.Common.BaseYearModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportVetCountryPreventiveMeasures", ReplyAction="http://tempuri.org/IReportFacade/ExportVetCountryPreventiveMeasuresResponse")]
        byte[] ExportVetCountryPreventiveMeasures(eidss.model.Reports.KZ.ProphylacticModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportVetCountrySanitaryMeasures", ReplyAction="http://tempuri.org/IReportFacade/ExportVetCountrySanitaryMeasuresResponse")]
        byte[] ExportVetCountrySanitaryMeasures(eidss.model.Reports.KZ.SanitaryModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportVetCountryPlannedDiagnosticTests", ReplyAction="http://tempuri.org/IReportFacade/ExportVetCountryPlannedDiagnosticTestsResponse")]
        byte[] ExportVetCountryPlannedDiagnosticTests(eidss.model.Reports.KZ.DiagnosticInvestigationModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportVetOblastPreventiveMeasures", ReplyAction="http://tempuri.org/IReportFacade/ExportVetOblastPreventiveMeasuresResponse")]
        byte[] ExportVetOblastPreventiveMeasures(eidss.model.Reports.KZ.ProphylacticModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportVetOblastSanitaryMeasures", ReplyAction="http://tempuri.org/IReportFacade/ExportVetOblastSanitaryMeasuresResponse")]
        byte[] ExportVetOblastSanitaryMeasures(eidss.model.Reports.KZ.SanitaryModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportVetOblastPlannedDiagnosticTests", ReplyAction="http://tempuri.org/IReportFacade/ExportVetOblastPlannedDiagnosticTestsResponse")]
        byte[] ExportVetOblastPlannedDiagnosticTests(eidss.model.Reports.KZ.DiagnosticInvestigationModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportLimTestResult", ReplyAction="http://tempuri.org/IReportFacade/ExportLimTestResultResponse")]
        byte[] ExportLimTestResult(eidss.model.Reports.Common.LimTestResultModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportLimSampleTransfer", ReplyAction="http://tempuri.org/IReportFacade/ExportLimSampleTransferResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.HumIdModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.AggregateActionsModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.VetIdModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimTestResultModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimTestModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimBatchTestModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.AggregateModel))]
        byte[] ExportLimSampleTransfer(eidss.model.Reports.Common.BaseIdModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportLimTest", ReplyAction="http://tempuri.org/IReportFacade/ExportLimTestResponse")]
        byte[] ExportLimTest(eidss.model.Reports.Common.LimTestModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportLimBatchTest", ReplyAction="http://tempuri.org/IReportFacade/ExportLimBatchTestResponse")]
        byte[] ExportLimBatchTest(eidss.model.Reports.Common.LimBatchTestModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportLimContainerDetails", ReplyAction="http://tempuri.org/IReportFacade/ExportLimContainerDetailsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.HumIdModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.AggregateActionsModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.VetIdModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimTestResultModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimTestModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimBatchTestModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.AggregateModel))]
        byte[] ExportLimContainerDetails(eidss.model.Reports.Common.BaseIdModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportLimContainerContent", ReplyAction="http://tempuri.org/IReportFacade/ExportLimContainerContentResponse")]
        byte[] ExportLimContainerContent(eidss.model.Reports.Common.LimContainerContentModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportLimAccessionIn", ReplyAction="http://tempuri.org/IReportFacade/ExportLimAccessionInResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.HumIdModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.AggregateActionsModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.VetIdModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimTestResultModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimTestModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimBatchTestModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.AggregateModel))]
        byte[] ExportLimAccessionIn(eidss.model.Reports.Common.BaseIdModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportOutbreak", ReplyAction="http://tempuri.org/IReportFacade/ExportOutbreakResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.HumIdModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.AggregateActionsModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.VetIdModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimTestResultModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimTestModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimBatchTestModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.AggregateModel))]
        byte[] ExportOutbreak(eidss.model.Reports.Common.BaseIdModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/ExportAdmEventLog", ReplyAction="http://tempuri.org/IReportFacade/ExportAdmEventLogResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.KZ.ProphylacticModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.KZ.SanitaryModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.KZ.DiagnosticInvestigationModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.SummaryByRayonDiagnosisAgeGroupsModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.GG.Hum60BJournalModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.GG.IntermediateInfectiousDiseaseSurrogateModel))]
        byte[] ExportAdmEventLog(eidss.model.Reports.Common.BaseIntervalModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportFacade/GetServiceVersion", ReplyAction="http://tempuri.org/IReportFacade/GetServiceVersionResponse")]
        System.Version GetServiceVersion();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportFacadeChannel : eidss.webclient.ReportService.IReportFacade, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportFacadeClient : System.ServiceModel.ClientBase<eidss.webclient.ReportService.IReportFacade>, eidss.webclient.ReportService.IReportFacade {
        
        public ReportFacadeClient() {
        }
        
        public ReportFacadeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportFacadeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportFacadeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportFacadeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] ExportHumAggregateCase(eidss.model.Reports.Common.AggregateModel model) {
            return base.Channel.ExportHumAggregateCase(model);
        }
        
        public byte[] ExportHumAggregateCaseSummary(eidss.model.Reports.Common.AggregateSummaryModel model) {
            return base.Channel.ExportHumAggregateCaseSummary(model);
        }
        
        public byte[] ExportHumCaseInvestigation(eidss.model.Reports.Common.HumIdModel model) {
            return base.Channel.ExportHumCaseInvestigation(model);
        }
        
        public byte[] ExportHumUrgentyNotification(eidss.model.Reports.Common.BaseIdModel model) {
            return base.Channel.ExportHumUrgentyNotification(model);
        }
        
        public byte[] ExportHumDiagnosisToChangedDiagnosis(eidss.model.Reports.Common.BaseIntervalModel model) {
            return base.Channel.ExportHumDiagnosisToChangedDiagnosis(model);
        }
        
        public byte[] ExportHumMonthlyMorbidityAndMortality(eidss.model.Reports.Common.BaseDateModel model) {
            return base.Channel.ExportHumMonthlyMorbidityAndMortality(model);
        }
        
        public byte[] ExportHumSummaryOfInfectiousDiseases(eidss.model.Reports.Common.BaseIntervalModel model) {
            return base.Channel.ExportHumSummaryOfInfectiousDiseases(model);
        }
        
        public byte[] ExportHumSerologyResearchCard(eidss.model.Reports.GG.LabSampleModel model) {
            return base.Channel.ExportHumSerologyResearchCard(model);
        }
        
        public byte[] ExportHumMicrobiologyResearchCard(eidss.model.Reports.GG.LabSampleModel model) {
            return base.Channel.ExportHumMicrobiologyResearchCard(model);
        }
        
        public byte[] ExportHumAntibioticResistanceCard(eidss.model.Reports.GG.LabSampleModel model) {
            return base.Channel.ExportHumAntibioticResistanceCard(model);
        }
        
        public byte[] ExportHum60BJournal(eidss.model.Reports.GG.Hum60BJournalModel model) {
            return base.Channel.ExportHum60BJournal(model);
        }
        
        public byte[] ExportHumMonthInfectiousDisease(eidss.model.Reports.GG.MonthInfectiousDiseaseModel model) {
            return base.Channel.ExportHumMonthInfectiousDisease(model);
        }
        
        public byte[] ExportHumMonthInfectiousDiseaseNew(eidss.model.Reports.GG.MonthInfectiousDiseaseModel model) {
            return base.Channel.ExportHumMonthInfectiousDiseaseNew(model);
        }
        
        public byte[] ExportHumIntermediateMonthInfectiousDisease(eidss.model.Reports.GG.IntermediateInfectiousDiseaseSurrogateModel model) {
            return base.Channel.ExportHumIntermediateMonthInfectiousDisease(model);
        }
        
        public byte[] ExportHumIntermediateMonthInfectiousDiseaseNew(eidss.model.Reports.GG.IntermediateInfectiousDiseaseSurrogateModel model) {
            return base.Channel.ExportHumIntermediateMonthInfectiousDiseaseNew(model);
        }
        
        public byte[] ExportHumAnnualInfectiousDisease(eidss.model.Reports.GG.AnnualInfectiousDiseaseModel model) {
            return base.Channel.ExportHumAnnualInfectiousDisease(model);
        }
        
        public byte[] ExportHumIntermediateAnnualInfectiousDisease(eidss.model.Reports.GG.IntermediateInfectiousDiseaseSurrogateModel model) {
            return base.Channel.ExportHumIntermediateAnnualInfectiousDisease(model);
        }
        
        public byte[] ExportHumFormN1(eidss.model.Reports.AZ.FormNo1SurrogateModel model) {
            return base.Channel.ExportHumFormN1(model);
        }
        
        public byte[] ExportHumDataQualityIndicators(eidss.model.Reports.AZ.DataQualityIndicatorsModel model) {
            return base.Channel.ExportHumDataQualityIndicators(model);
        }
        
        public byte[] ExportHumDataQualityIndicatorsRayons(eidss.model.Reports.AZ.DataQualityIndicatorsModel model) {
            return base.Channel.ExportHumDataQualityIndicatorsRayons(model);
        }
        
        public byte[] ExportHumSummaryByRayonDiagnosisAgeGroups(eidss.model.Reports.AZ.SummaryByRayonDiagnosisAgeGroupsModel model) {
            return base.Channel.ExportHumSummaryByRayonDiagnosisAgeGroups(model);
        }
        
        public byte[] ExportHumComparativeAZReport(eidss.model.Reports.AZ.ComparativeSurrogateModel model) {
            return base.Channel.ExportHumComparativeAZReport(model);
        }
        
        public byte[] ExportHumExternalComparativeReport(eidss.model.Reports.AZ.ExternalComparativeSurrogateModel model) {
            return base.Channel.ExportHumExternalComparativeReport(model);
        }
        
        public byte[] ExportHumMainIndicatorsOfAFPSurveillance(eidss.model.Reports.AZ.AFPModel model) {
            return base.Channel.ExportHumMainIndicatorsOfAFPSurveillance(model);
        }
        
        public byte[] ExportHumAdditionalIndicatorsOfAFPSurveillance(eidss.model.Reports.AZ.AFPModel model) {
            return base.Channel.ExportHumAdditionalIndicatorsOfAFPSurveillance(model);
        }
        
        public byte[] ExportHumWhoMeaslesRubellaReport(eidss.model.Reports.Common.BaseDateModel model) {
            return base.Channel.ExportHumWhoMeaslesRubellaReport(model);
        }
        
        public byte[] ExportHumComparativeReportOfTwoYears(eidss.model.Reports.AZ.ComparativeTwoYearsSurrogateModel model) {
            return base.Channel.ExportHumComparativeReportOfTwoYears(model);
        }
        
        public byte[] ExportVeterinaryCasesReport(eidss.model.Reports.AZ.VetCasesSurrogateModel model) {
            return base.Channel.ExportVeterinaryCasesReport(model);
        }
        
        public byte[] ExportVeterinaryLaboratoriesAZReport(eidss.model.Reports.AZ.VetLabSurrogateModel model) {
            return base.Channel.ExportVeterinaryLaboratoriesAZReport(model);
        }
        
        public byte[] ExportVetAggregateCase(eidss.model.Reports.Common.AggregateModel model) {
            return base.Channel.ExportVetAggregateCase(model);
        }
        
        public byte[] ExportVetAggregateCaseSummary(eidss.model.Reports.Common.AggregateSummaryModel model) {
            return base.Channel.ExportVetAggregateCaseSummary(model);
        }
        
        public byte[] ExportVetAggregateCaseActions(eidss.model.Reports.Common.AggregateActionsModel model) {
            return base.Channel.ExportVetAggregateCaseActions(model);
        }
        
        public byte[] ExportVetAggregateCaseActionsSummary(eidss.model.Reports.Common.AggregateActionsSummaryModel model) {
            return base.Channel.ExportVetAggregateCaseActionsSummary(model);
        }
        
        public byte[] ExportVetAvianInvestigation(eidss.model.Reports.Common.VetIdModel model) {
            return base.Channel.ExportVetAvianInvestigation(model);
        }
        
        public byte[] ExportVetLivestockInvestigation(eidss.model.Reports.Common.VetIdModel model) {
            return base.Channel.ExportVetLivestockInvestigation(model);
        }
        
        public byte[] ExportVetActiveSurveillanceSampleCollected(eidss.model.Reports.Common.BaseIdModel model) {
            return base.Channel.ExportVetActiveSurveillanceSampleCollected(model);
        }
        
        public byte[] ExportVetSamplesCount(eidss.model.Reports.Common.BaseYearModel model) {
            return base.Channel.ExportVetSamplesCount(model);
        }
        
        public byte[] ExportVetSamplesBySampleType(eidss.model.Reports.Common.BaseYearModel model) {
            return base.Channel.ExportVetSamplesBySampleType(model);
        }
        
        public byte[] ExportVetSamplesBySampleTypesWithinRegions(eidss.model.Reports.Common.BaseYearModel model) {
            return base.Channel.ExportVetSamplesBySampleTypesWithinRegions(model);
        }
        
        public byte[] ExportVetYearlySituation(eidss.model.Reports.Common.BaseYearModel model) {
            return base.Channel.ExportVetYearlySituation(model);
        }
        
        public byte[] ExportVetActiveSurveillance(eidss.model.Reports.Common.BaseYearModel model) {
            return base.Channel.ExportVetActiveSurveillance(model);
        }
        
        public byte[] ExportVetCountryPreventiveMeasures(eidss.model.Reports.KZ.ProphylacticModel model) {
            return base.Channel.ExportVetCountryPreventiveMeasures(model);
        }
        
        public byte[] ExportVetCountrySanitaryMeasures(eidss.model.Reports.KZ.SanitaryModel model) {
            return base.Channel.ExportVetCountrySanitaryMeasures(model);
        }
        
        public byte[] ExportVetCountryPlannedDiagnosticTests(eidss.model.Reports.KZ.DiagnosticInvestigationModel model) {
            return base.Channel.ExportVetCountryPlannedDiagnosticTests(model);
        }
        
        public byte[] ExportVetOblastPreventiveMeasures(eidss.model.Reports.KZ.ProphylacticModel model) {
            return base.Channel.ExportVetOblastPreventiveMeasures(model);
        }
        
        public byte[] ExportVetOblastSanitaryMeasures(eidss.model.Reports.KZ.SanitaryModel model) {
            return base.Channel.ExportVetOblastSanitaryMeasures(model);
        }
        
        public byte[] ExportVetOblastPlannedDiagnosticTests(eidss.model.Reports.KZ.DiagnosticInvestigationModel model) {
            return base.Channel.ExportVetOblastPlannedDiagnosticTests(model);
        }
        
        public byte[] ExportLimTestResult(eidss.model.Reports.Common.LimTestResultModel model) {
            return base.Channel.ExportLimTestResult(model);
        }
        
        public byte[] ExportLimSampleTransfer(eidss.model.Reports.Common.BaseIdModel model) {
            return base.Channel.ExportLimSampleTransfer(model);
        }
        
        public byte[] ExportLimTest(eidss.model.Reports.Common.LimTestModel model) {
            return base.Channel.ExportLimTest(model);
        }
        
        public byte[] ExportLimBatchTest(eidss.model.Reports.Common.LimBatchTestModel model) {
            return base.Channel.ExportLimBatchTest(model);
        }
        
        public byte[] ExportLimContainerDetails(eidss.model.Reports.Common.BaseIdModel model) {
            return base.Channel.ExportLimContainerDetails(model);
        }
        
        public byte[] ExportLimContainerContent(eidss.model.Reports.Common.LimContainerContentModel model) {
            return base.Channel.ExportLimContainerContent(model);
        }
        
        public byte[] ExportLimAccessionIn(eidss.model.Reports.Common.BaseIdModel model) {
            return base.Channel.ExportLimAccessionIn(model);
        }
        
        public byte[] ExportOutbreak(eidss.model.Reports.Common.BaseIdModel model) {
            return base.Channel.ExportOutbreak(model);
        }
        
        public byte[] ExportAdmEventLog(eidss.model.Reports.Common.BaseIntervalModel model) {
            return base.Channel.ExportAdmEventLog(model);
        }
        
        public System.Version GetServiceVersion() {
            return base.Channel.GetServiceVersion();
        }
    }
}
