//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version Beta 1.2
//
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Beta Version
//
package com.WSParser.WebServices.EidssService;

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class BaseReferenceItem implements KvmSerializable {

    public String NAMESPACE =" http://bv.com/eidss";
    public long id;
    public String name;
    
    public BaseReferenceItem(){}
    
    public BaseReferenceItem(SoapObject soapObject){
    
        if (soapObject.hasProperty("Name"))
        {
            Object obj = soapObject.getProperty("Name");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j12 =(SoapPrimitive) soapObject.getProperty("Name");
                name = j12.toString();
            }
        }
        if (soapObject.hasProperty("Id"))
        {
            Object obj = soapObject.getProperty("Id");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j25 =(SoapPrimitive) soapObject.getProperty("Id");
                id = Long.parseLong(j25.toString());
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
    switch(arg0){
        case 0:
            return name;
        case 1:
            return id;
    }
    return null;
    }
    @Override
    public int getPropertyCount() {
        return 2;
    }
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
    switch(index){
        case 0:
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Name";
            break;
        case 1:
            info.type = Long.class;
            info.name = "Id";
            break;
    }
    }
    @Override
    public void setProperty(int index, Object value) {
    switch(index){
        case 0:
        name = value.toString() ;
        break;
        case 1:
        id = Long.parseLong(value.toString()) ;
        break;
}
}
}
