//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version Beta 1.2
//
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Beta Version
//
package com.WSParser.WebServices.EidssService;

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import android.content.ContentValues;

public class GisBaseReferenceTranslationRaw implements KvmSerializable {

    public String NAMESPACE =" http://bv.com/eidss";
    public long idfsBaseReference;
    public String strTranslation;
    public String strLanguage;
    
    public ContentValues ContentValues()
    {
    	ContentValues ret = new ContentValues();
        ret.put("idfsBaseReference", idfsBaseReference);
        ret.put("strTranslation", strTranslation);
        ret.put("strLanguage", strLanguage);
        return ret;
    }
    
    public GisBaseReferenceTranslationRaw(){}
    
    public GisBaseReferenceTranslationRaw(SoapObject soapObject){
    
        if (soapObject.hasProperty("idfsBaseReference"))
        {
            Object obj = soapObject.getProperty("idfsBaseReference");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j13 =(SoapPrimitive) soapObject.getProperty("idfsBaseReference");
                idfsBaseReference = Long.parseLong(j13.toString());
            }
        }
        if (soapObject.hasProperty("strTranslation"))
        {
            Object obj = soapObject.getProperty("strTranslation");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j14 =(SoapPrimitive) soapObject.getProperty("strTranslation");
                strTranslation = j14.toString();
            }
        }
        if (soapObject.hasProperty("strLanguage"))
        {
            Object obj = soapObject.getProperty("strLanguage");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j15 =(SoapPrimitive) soapObject.getProperty("strLanguage");
                strLanguage = j15.toString();
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
    switch(arg0){
        case 0:
            return idfsBaseReference;
        case 1:
            return strTranslation;
        case 2:
            return strLanguage;
    }
    return null;
    }
    @Override
    public int getPropertyCount() {
        return 3;
    }
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
    switch(index){
        case 0:
            info.type = Long.class;
            info.name = "idfsBaseReference";
            break;
        case 1:
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "strTranslation";
            break;
        case 2:
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "strLanguage";
            break;
    }
    }
    @Override
    public void setProperty(int index, Object value) {
    switch(index){
        case 0:
        idfsBaseReference = Long.parseLong(value.toString()) ;
        break;
        case 1:
        strTranslation = value.toString() ;
        break;
        case 2:
        strLanguage = value.toString() ;
        break;
}
}
}
